### ISSUE TITLE
Prepare baseline model for fine-tuning

### ISSUE THREAD

**Issue by fairwell-coding** [fairwell-coding/nlp#1]
Prepare working code of base line model: https://huggingface.co/t5-large
This includes model loading, potentially added preprocessing, evaluation code and model distillation (basically training-ready)
Include distilled version in repo and properly document the distillation outcomes for report
Prepare encoder freezing for training: https://discuss.huggingface.co/t/how-to-freeze-layers-using-trainer/4702

Once this task is resolved model training should be possible straight away.

**Comment by SteveineiterTU** [comment]
Use the highest distil factor at distillation

**Comment by sayanxtreme** [comment]
Using this as baseline?
python make_student.py t5-small t5_small_6_3 6 3

**Comment by sayanxtreme** [comment]
t5_small_6_3 finetuning without layer freezing:
https://huggingface.co/sayanmandal/t5-small_6_3-hi_en-to-en
Use this command to generate model:
python make_student.py t5-small t5_small_6_3 6 3
