### ISSUE TITLE
Distill from T5

### ISSUE THREAD

**Issue by SteveineiterTU** [fairwell-coding/nlp#11]
model distillation (basically training-ready) from T5. Should be possible to reuse the one from Issue "Prepare baseline model for fine-tuning #1"

Resources:
- https://github.com/huggingface/transformers/blob/main/examples/research_projects/seq2seq-distillation/distillation.py
- https://discuss.huggingface.co/t/questions-on-distilling-from-t5/1193/10

**Comment by fairwell-coding** [comment]
not necessary, distillation only happens once in #1 and #4 covers the rest
