### ISSUE TITLE
Finetune baseline model with eng-hindi

### ISSUE THREAD

**Issue by fairwell-coding** [fairwell-coding/nlp#2]
Finetune model until reasonable eng-hindi translation is possible 
While progress can be seen on metrics, reasonable Hindi output should be verified by Sayan.
Training may be done in several steps (and different people) by use of regular checkpoints.

**Comment by sayanxtreme** [comment]
Source: hi_en
Target: en
Somehow en to hi_en was not converging. Will need to look further on it if there's time.
https://huggingface.co/sayanmandal/t5-small_6_3-hi_en-to-en
